version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRERS_DB=market_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1111
    ports:
      - "5432:5432"

  django:
    build: .
    command: bash -c "cd src && python manage.py makemigrations
                      && python manage.py migrate
                      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
